version: '3.7'

services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
      - source: hapi-extra-classes
        target: /app/extra-classes
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    ports:
      - "5000:5432"
    volumes:
      - ./hapi.postgress.data:/var/lib/postgresql/data

configs:
  hapi:
    file: ./hapi.application.yaml
  hapi-extra-classes:
    file: ./hapi-extra-classes

  fhir:
    custom-bean-packages: src.main.java.ca.uhn.fhir.jpa.starter.common.validation
    custom-interceptor-classes: src.main.java.ca.uhn.fhir.jpa.starter.common.validation.RepositoryValidationInterceptorFactoryDstu3

  datasource:
    url: 'jdbc:postgresql://db:5432/hapi'
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      hibernate.search.enabled: false
